[ui]
editor = "nvim"
pager = "delta"
diff-formatter = ["difft", "--color=always", "$left", "$right"]

[user]
name = "Owen Campbell"
email = "owen.campbell@empiria.co.uk"

[signing]
behaviour = "own"
backend = "ssh"
key = "~/.ssh/git.pub"

[fix.tools.ruff]
command = ["ruff", "format", "-"]
patterns = ["glob:'**/*.py'"]
